# Generated by Django 5.2.5 on 2025-09-02 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userredeembalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userredeem',
            name='status',
        ),
        migrations.AlterField(
            model_name='userredeem',
            name='points_used',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userredeem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RedeemTransaction',
        ),
        migrations.DeleteModel(
            name='UserRedeemBalance',
        ),
    ]
