# Generated by Django 5.2.5 on 2025-09-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='redeem_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
