# Generated by Django 5.2.5 on 2025-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_alt_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], default='', max_length=20),
        ),
    ]
