# Generated by Django 5.2.5 on 2025-10-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_alt_delivery_address_and_more'),
        ('branch', '0003_branch_created_at_branch_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
