# Generated by Django 5.2.5 on 2025-09-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaddons',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='product.product'),
        ),
    ]
