# Generated by Django 5.2.5 on 2025-09-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productaddons_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='redeem_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
