# Generated by Django 5.2.5 on 2025-09-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_alt_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
