# Generated by Django 5.2.5 on 2025-09-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_image_alt_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
    ]
