# Generated by Django 5.2.5 on 2025-09-05 06:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_favorite_unique_together'),
        ('product', '0008_remove_product_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('product', 'user')},
        ),
    ]
