# Generated by Django 5.2.5 on 2025-10-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_created_at_branch_updated_at'),
        ('favorites', '0003_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
