# Generated by Django 5.2.5 on 2025-09-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
