# Generated by Django 5.2.5 on 2025-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
