# Generated by Django 5.2.5 on 2025-09-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_product_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
