# Generated by Django 5.2.5 on 2025-09-04 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_latitude_alter_branch_longitude'),
        ('order', '0006_orderitem_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='branch',
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
