# Generated by Django 5.2.5 on 2025-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_discount_remove_orderitem_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine-in', 'Dine-in'), ('take-away', 'Take-away')], default='dine-in', max_length=50),
        ),
    ]
