# Generated by Django 5.2.5 on 2025-09-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine-in', 'Dine-in'), ('take-away', 'Take-away')], default='Dine-in', max_length=50),
        ),
    ]
