# Generated by Django 5.2.5 on 2025-09-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_discount_alter_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
