# Generated by Django 5.2.5 on 2025-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('dine-in', 'Dine-in'), ('take-away', 'Take-away')], default='dine-in', max_length=50, null=True),
        ),
    ]
